import { useState, useEffect } from 'react';
import { Brain, Sparkles, PenLine, Clock } from 'lucide-react';
import {
  Card,
  CardContent,
  CardTitle,
  Input,
  TextArea,
  Select,
  Badge,
} from '@/components/ui';
import { ISSUE_CATEGORIES } from '@/lib/constants';
import { cn } from '@/lib/utils';
import type { AIAnalysisResult, AICategory, AISeverity, AIDepartment } from '@/types/aiAnalysis';

// ─── Types ───

export interface ReviewedAnalysis {
  category: AICategory;
  severity: AISeverity;
  department: AIDepartment;
  title: string;
  description: string;
  confidence: number;
}

interface AIReviewPanelProps {
  result: AIAnalysisResult;
  onChange: (reviewed: ReviewedAnalysis) => void;
  className?: string;
}

// ─── Constants ───

const SEVERITY_OPTIONS = [
  { value: 'low', label: 'Low — Minor inconvenience' },
  { value: 'medium', label: 'Medium — Needs attention soon' },
  { value: 'high', label: 'High — Safety concern' },
  { value: 'critical', label: 'Critical — Immediate danger' },
];

const DEPARTMENT_OPTIONS = [
  { value: 'public_works', label: 'Public Works' },
  { value: 'water_supply', label: 'Water Supply' },
  { value: 'electricity', label: 'Electricity' },
  { value: 'sanitation', label: 'Sanitation' },
  { value: 'roads', label: 'Roads & Transport' },
  { value: 'parks', label: 'Parks & Recreation' },
  { value: 'general', label: 'General' },
];

const MAX_DESCRIPTION_LENGTH = 500;

// ─── Component ───

export function AIReviewPanel({ result, onChange, className }: AIReviewPanelProps) {
  const [edited, setEdited] = useState<ReviewedAnalysis>({
    category: result.category,
    severity: result.severity,
    department: result.department,
    title: result.title,
    description: result.description,
    confidence: result.confidence,
  });

  // Track which fields were manually edited
  const [editedFields, setEditedFields] = useState<Set<string>>(new Set());

  // Notify parent on change
  useEffect(() => {
    onChange(edited);
  }, [edited, onChange]);

  const handleChange = (field: keyof ReviewedAnalysis, value: string) => {
    setEdited((prev) => ({ ...prev, [field]: value }));
    if (!editedFields.has(field)) {
      setEditedFields((prev) => new Set(prev).add(field));
    }
  };

  const confidence = result.confidence;
  const confidenceConfig = getConfidenceConfig(confidence);

  return (
    <Card className={cn('animate-slide-up overflow-hidden', className)}>
      {/* Header */}
      <div className="flex items-start justify-between gap-3">
        <CardTitle className="flex items-center gap-2">
          <Brain className="h-5 w-5 text-secondary-600 dark:text-secondary-400" />
          AI Analysis Review
        </CardTitle>
        <Badge variant={confidenceConfig.variant} size="sm">
          {confidenceConfig.label} ({confidence}%)
        </Badge>
      </div>

      {/* Metadata */}
      <div className="mt-2 flex flex-wrap items-center gap-3 text-[11px] text-neutral-500 dark:text-neutral-400">
        <span className="inline-flex items-center gap-1">
          <Sparkles className="h-3 w-3" />
          Generated by Gemini AI
        </span>
        <span className="inline-flex items-center gap-1">
          <Clock className="h-3 w-3" />
          Analyzed just now
        </span>
      </div>

      <CardContent className="mt-5 space-y-4">
        {/* Title */}
        <FieldWrapper label="Suggested Title" edited={editedFields.has('title')}>
          <Input
            value={edited.title}
            onChange={(e) => handleChange('title', e.target.value)}
            placeholder="Issue title"
          />
        </FieldWrapper>

        {/* Category + Severity row */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <FieldWrapper label="Category" edited={editedFields.has('category')}>
            <Select
              value={edited.category}
              onChange={(e) => handleChange('category', e.target.value)}
              options={ISSUE_CATEGORIES.map((c) => ({ value: c.value, label: c.label }))}
            />
          </FieldWrapper>

          <FieldWrapper label="Severity" edited={editedFields.has('severity')}>
            <Select
              value={edited.severity}
              onChange={(e) => handleChange('severity', e.target.value)}
              options={SEVERITY_OPTIONS}
            />
          </FieldWrapper>
        </div>

        {/* Department */}
        <FieldWrapper label="Responsible Department" edited={editedFields.has('department')}>
          <Select
            value={edited.department}
            onChange={(e) => handleChange('department', e.target.value)}
            options={DEPARTMENT_OPTIONS}
          />
        </FieldWrapper>

        {/* Description with character counter */}
        <FieldWrapper label="Description" edited={editedFields.has('description')}>
          <div className="relative">
            <TextArea
              value={edited.description}
              onChange={(e) => {
                if (e.target.value.length <= MAX_DESCRIPTION_LENGTH) {
                  handleChange('description', e.target.value);
                }
              }}
              placeholder="Detailed description of the issue..."
              className="min-h-[100px]"
            />
            <div className="mt-1 flex justify-end">
              <span
                className={cn(
                  'text-[11px]',
                  edited.description.length > MAX_DESCRIPTION_LENGTH * 0.9
                    ? 'text-danger-500'
                    : 'text-neutral-400'
                )}
              >
                {edited.description.length}/{MAX_DESCRIPTION_LENGTH}
              </span>
            </div>
          </div>
        </FieldWrapper>
      </CardContent>
    </Card>
  );
}

// ─── Sub-components ───

function FieldWrapper({
  label,
  edited,
  children,
}: {
  label: string;
  edited: boolean;
  children: React.ReactNode;
}) {
  return (
    <div>
      <div className="flex items-center gap-2 mb-1.5">
        <label className="text-sm font-medium text-text-primary dark:text-neutral-200">
          {label}
        </label>
        {edited && (
          <span className="inline-flex items-center gap-1 text-[10px] font-medium text-accent-600 dark:text-accent-400 bg-accent-50 dark:bg-accent-500/10 px-1.5 py-0.5 rounded-md">
            <PenLine className="h-2.5 w-2.5" />
            Edited
          </span>
        )}
      </div>
      {children}
    </div>
  );
}

// ─── Helpers ───

function getConfidenceConfig(confidence: number): {
  label: string;
  variant: 'success' | 'accent' | 'danger';
} {
  if (confidence >= 90) return { label: 'Excellent', variant: 'success' };
  if (confidence >= 70) return { label: 'Good', variant: 'accent' };
  return { label: 'Needs Review', variant: 'danger' };
}
